<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	<!-- Favicon
	<meta name="msapplication-TileColor" content="#D83434">
	<meta name="msapplication-TileImage" content="path/to/tileicon.png">
	<link rel="shortcut icon" href="../../docs-assets/ico/favicon.png" type="image/png">
	<link rel="icon" href="../../docs-assets/ico/favicon.png" type="image/png">
	<link href="/apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed">
	<link href="/apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72">
	<link href="/apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114">
	<link href="/apple-touch-icon-144x144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144">
	-->
	<!--[if IE]><link rel="shortcut icon" href="path/to/favicon.ico"><![endif]-->
	<!-- or, set /favicon.ico for IE10 win -->
	
	<title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
	<?= $this->html->css('bootstrap');?>

    <!-- Custom styles for this template -->
	<?= $this->html->css('starter-template');?>
    <!--<link href="starter-template.css" rel="stylesheet">-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

 
	  
	
    <div class="container">
		<p>&nbsp;</p>  
		<p>&nbsp;</p> 
		<div class="starter-template">
			<h1>Bootstrap starter template</h1>
				<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
		</div>

	</div><!-- /.container -->

	<div class="row debug">
		<div class="col-lg-4">
			<pre><?php var_dump($_SERVER); ?></pre>
		</div>
		<div class="col-lg-4">
			<pre><?php var_dump(get_defined_constants(true)); ?></pre>
		</div>
		<div class="col-lg-4">
			<pre><?php var_dump(get_defined_vars()); ?></pre>
		</div>

	</div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<?= $this->html->script('https://code.jquery.com/jquery-1.10.2.min.js'); ?>
	<?= $this->html->js('bootstrap'); ?>
    <!--<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="./www_root/script/bootstrap.min.js"></script>-->
  </body>
</html>